- .github/workflows/ccpp.yml
- include/gtensor/gtensor.h
- tests/test_complex.cxx
- std::complex works as long as the header is included after
hip_runtime (imported via device_backend via device_runtime).
For some reason this didn't come up in 3.3.0.
- switch ci back to 3.5.0 since it's so much faster (and tends
to be more strict, so it should work for 3.3.0 as well).
> hip: fix complex test for ROCm 3.5.0

- include/gtensor/sarray.h
This is just mimicking standard container behavior.
> sarray: add data() methods

- .github/workflows/ccpp.yml
- include/gtensor/space.h
rocthrust has an older verison, but uses the newer API.
> fix for rocthrust 3.7

- include/gtensor/device_backend.h
- include/gtensor/gtensor.h
- include/gtensor/space.h
Usually, cudaFree() is synchronizing, and that needs to be done in the
caching allocator, too, since it's not a good idea to free memory while
it's still being used in a concurrently executing kernel.
> fix: call sync in caching deallocate

- include/gtensor/gstrided.h
- tests/test_view.cxx
This provides a better error message when doing things like
(gtensor<int, 2>).view(0, 1, _all), while still allowing
newaxis.
> gview: better error on too many args

- .github/workflows/sycl.yml
- include/gtensor/reductions.h
- run-gtests.sh
Installs latest version, which has it's own drawbacks but the
repo does not keep older versions anyway. Note that this is not
as robust as it could be, because package names could still
change. Installing all of basekit would be more robust as the
documented way of installing, but it would slow the build down
a lot.
> ci: make sycl version independent

- include/gtensor/assign.h
- include/gtensor/gcontainer.h
- include/gtensor/gfunction.h
- include/gtensor/gtensor.h
- include/gtensor/gtensor_span.h
- include/gtensor/gview.h
- include/gtensor/reductions.h
- include/gtensor/sarray.h
- tests/CMakeLists.txt
- tests/test_assign.cxx
- tests/test_gtensor.cxx
- tests/test_gtensor_span.cxx
- tests/test_sarray.cxx
- tests/test_view.cxx
mirrors operator() for proper const behavior. Does not support
index by initializer list, this would provide a redundant
syntax for literal indexes and while it looks nice in
tests and examples, it doesn't seem to be necessary.
> add operator[] for index by shape

- .github/workflows/ccpp.yml
github switched to ubuntu-latest = 20.04
> ci: use 18.04 for older compilers

- .gitignore
- include/gtensor/gstrided.h
- include/gtensor/gtensor.h
- include/gtensor/gtensor_span.h
- include/gtensor/helper.h
- include/gtensor/macros.h
- include/gtensor/sarray.h
- include/gtensor/span.h
This add some `GT_INLINE` to functions that should be usable from the device (ie., which I needed to be usable on the device), and also adds `inline` to  `GT_INLINE` macro, which was missing in the CUDA case.
> little bits and pieces

- include/gt-fft/backend/cuda.h
- include/gt-fft/backend/sycl.h
- include/gt-fft/fft.h
cuFFT, particularly starting with CUDA 11, will modify input
with out of place transform on c2r. None of the underlying
libraries advertise const input, so to be safe we will remove
this promise as well, even though it appears to be true for
the other transforms.
> fft: remove const on input

- include/gtensor/gtensor_span.h
It's probably not what usually should be done, but it may sometimes make sense,
if only to work around some other limitation like I'm currently doing
(the other limitation being that one can't createa view on the device,
which probably should be enabled, too.)
> allow adapt() to be called on the device

- include/gtensor/gfunction.h
- include/gtensor/reductions.h
- tests/test_expression.cxx
- tests/test_reductions.cxx
They're kinda related, `gt::abs` is needed to calculate the infinity norm, and the infinity norm is useful to check results of
`gt::sin` as an example.
> add some unary functions and norm_linf

- CMakeLists.txt
- cmake/CPM.cmake
- examples/CMakeLists.txt
It makes it easier to deal with a choice of pre-installed packages or
downloading them on demand, including overriding things to point to
a local copy when desired for development.
It'd help more if there was more than googletest that we use it for, but
that's it at this time. At least the googletest it downloads now doesn't
have the annoying warnings about ancient cmake.
> use CPM as cmake package manager

- CMakeLists.txt
- benchmarks/CMakeLists.txt
- benchmarks/bench_assign.cxx
- include/gtensor/assign.h
- tests/test_gtensor.cxx
Doing some semi-arbitrary mapping between 4-d index space and threads/blocks is fragile, e.g., 
I hit the case where blockIdx.z exceeds the allow limit.
Using 1-d index space for launch and then calculating back a 4-d index is something that could be detrimental to performance, due to the integer divisions, but at least in the included benchmark it essentially doesn't make a difference (it's actually slightly faster on V100 for the particular case.)
There's definitely more that could be done, including
* same for other dimensionality
* don't map every index to a new thread in the first place, but map to enough threads and then loop.
* avoid mapping back to multi-d in the first place where the underlying storage is contiguous (that probably needs bigger changes in gtensor to know when that …
> implement 4d assign based on 1d block/thread index, benchmark

- benchmarks/ij_deriv.cxx
- include/gtensor/device_backend.h
- include/gtensor/gtensor_storage.h
- include/gtensor/space.h
- src/cgtensor.cxx
- tests/test_adapt.cxx
- tests/test_device_backend.cxx
This is just part of some bigger revamp of things (which I haven't even completed).
My particular motivation was being able to support standard allocators not only in thrust but also gtensor_storage, so that whoever is using gtensor can choose their preferred pool allocator or whatever. However, it's not nearly there yet, instead it opened the opportunity to do some more not quite directly related refactoring.
In particular, I'd like to make `gtensor_storage` and `thrust::device/host_vector` more directly interchangeable, forming a separate layer from, e.g., the allocator. I'd also like to see `gtensor_storage`'s implementation to be less directly dependent on whether the underlying storage is on the host, the device, managed or whatever. For now, this PR makes things a bit more …
> work towards standard allocator in gtensor_storage

- benchmarks/ij_deriv.cxx
- include/gtensor/device_backend.h
- include/gtensor/device_copy.h
- include/gtensor/gtensor_storage.h
- include/gtensor/memset.h
- src/cgtensor.cxx
- tests/test_device_backend.cxx
- tests/test_fft.cxx
- tests/test_gtensor_storage.cxx
It's kinda beyond actual allocator stuff, more of a some ongoing reorganization of the backend stuff. In particular, the copy and memset functions are now put into `struct ops` in the various `cuda`/`hip`/ etc namespaces.
> more allocator-related reorg

- include/gtensor/assign.h
- include/gtensor/gfunction.h
- tests/test_expression.cxx
This fixes a bug in unary `gfunction::size()`, and adds it in the binary case.
This should fix one of the sycl build errors.
> gfunction fixes

- include/gtensor/device_backend.h
- include/gtensor/gfunction.h
I get a bunch of `can't call a __host__ function from a __host__ __device__ function` warnings, and most of them are inside of thrust, so I can't easily do anything about them, but here's a couple that can be worked around.
> fix a couple of warnings

- include/gtensor/allocator.h
- include/gtensor/space.h
- tests/test_gtensor.cxx
- tests/test_thrust_ext.cxx
- tests/test_view.cxx
This separates out the caching allocator into a separate file, and introduces `GTENSOR_DEFAULT_{HOST,DEVICE}_ALLOCATOR` macros which can be set to override the default allocator.
Though by now I think that, for my purposes, I'll rather make my own variant of `gt::gtensor` that allow me to use my choice of allocator without relying on macro hackery.
> allocator: allow for overriding default allocator

- examples/src/daxpy.cxx
- examples/src/mult_table.cxx
- include/gtensor/allocator.h
- include/gtensor/device_backend.h
- include/gtensor/expression.h
- include/gtensor/gtensor.h
- include/gtensor/gtensor_forward.h
- include/gtensor/gtensor_span.h
- include/gtensor/space.h
- tests/test_gtensor.cxx
There is certainly some more refactoring / generalizing backends to come, but this I think is it in terms of adding flexibility to choose an allocator (as well as backend storage).
The first part is a bit of work towards having different tags for `cuda`, `hip`, etc, and having `device` just be an alias for whatever is default. However, this didn't go very far as other parts aren't really ready for it -- in particular, `gtensor_storage` is still using plain pointers, which are obviously indistinguishable between `cuda`, `hip`, etc, or even `host`.
The second part essentially turns `gtensor` into `gtensor_container`, which is now templated by the underlying storage (`EC`, take from xtensor, I suppose short for `element container`).  `gtensor` itself became an alias, preserving its template …
> finish (hopefully) allocator related work

- include/gtensor/complex_ops.h
- include/gtensor/gfunction.h
- tests/test_complex.cxx
- tests/test_expression.cxx
Fixes #110. (Actually, `gt::exp` already exists -- this just adds tests for it.)
> add tests for gt::cos, gt::exp (incl complex)

- CMakeLists.txt
- tests/test_expression.cxx
Needed for hybrid language codes, e.g. GENE uses Fortran & C++
> sycl: use -fsycl for C++ only

- benchmarks/CMakeLists.txt
- benchmarks/bench_hypz.cxx
This is a sample kernel taking from GENE that has a larger stencil, calculating some hyperviscosity term.
This is actually entirely untested right now (well, it does compile with CUDA, at least). I took most of the actual code from GENE, so that should be fine, but it's still possible that I screwed up the fields passed into it...
> bench: add bench_hypz

- CMakeLists.txt
This avoids hassles when including gtensor via `add_subdirectory()` / CPM.
> build: use "option" instead of setting a cache variable

- include/gtensor/macros.h
This bounds checking is expensive, and one might want to build one's code
with asserts enabled, but without incurring the bounds checking overhead.
> don't enable GT_BOUNDSCHECK based on NDEBUG

- .github/workflows/ccpp.yml
- CMakeLists.txt
Fixes issue with CMakeLists.txt in multi-level add_subdirectory,
where target is defined in a different file.
> cmake: use TARGET_DIRECTORY for source helper

- .github/workflows/sycl.yml
- CMakeLists.txt
Note that ILP64 is still required if using a CPU SYCL backend
> sycl: use LP64, works with GPU backends

- include/gt-blas/backend/sycl.h
- include/gtensor/backend_sycl_device.h
- include/gtensor/backend_thrust.h
- include/gtensor/device_backend.h
- include/gtensor/gtensor_storage.h
- include/gtensor/space_forward.h
- include/gtensor/thrust_ext.h
- tests/test_gtensor_storage.cxx
- tests/test_lapack.cxx
Uses gtensor RAII classes for temp memory, so things are cleaned up in case of failures, and so the memory pool can be used. Also adds a limited getrf_npvt API, which has a limitation that it requires contiguous matrices in input.
> sycl gt-blas improvements

- include/gtensor/macros.h
This should address #153 printing out the blocks and threads if the launch fails.
> Launch check

- include/gtensor/allocator.h
- include/gtensor/defs.h
- include/gtensor/device_backend.h
- include/gtensor/gtensor_forward.h
- include/gtensor/pointer_traits.h
- include/gtensor/space.h
- include/gtensor/space_forward.h
The change away from thrust as default backend actually caused me quite some breakage, and life gets easier if thrust backend storage is still supported even though when it's not used by default.
> support thrust backend storage even if not used as default

- include/gtensor/assign.h
- tests/test_assign.cxx
Assign check is too strict, can broadcast if RHS has 1 in any
dimension. See calc_index in strides.h.
> fix assign broadcast

- include/gtensor/gtensor_storage.h
For non thrust backend, anything that does a move assignment of an owning gtensor object will result in move assignment of the underlying gtensor_storage, which was not correctly deallocating the existing destination data and resulting in memory leaks.
> storage: fix memory leak on move assignment

- include/gtensor/backend_cuda.h
- include/gtensor/backend_hip.h
- include/gtensor/backend_sycl.h
- include/gtensor/device_backend.h
Use common stream classes. The existing code relies on each backend defining them correctly, with no help from the compiler.
Note that the hip and cuda backends still use a subclass that adds get_execution_policy - this is used by thrust reductions. Perhaps there is a more elegant way of handling this. It could be part of the interface, and sycl has a dummy implementation. Or sycl could have an implementation using oneDPL, but that makes us even more dependent on oneAPI vs SYCL standard.
> stream: refactor stream view and owning classes

- include/gtensor/assign.h
- include/gtensor/defs.h
- include/gtensor/gtensor.h
- include/gtensor/gtensor_storage.h
- include/gtensor/operator.h
- include/gtensor/reductions.h
Does not change external interface (shape_type is still int sarray).
This should make sure there is no int overflow in internal index
calculations. Note that reshape could still overflow, but the
assert that the sizes stayed the same in the implementation should
at least catch it in debug builds.
> indexing: use size_type for flat index, nd kernel

- CMakeLists.txt
- cmake/target-gtensor-sources-macro.cmake
- gtensor-config.cmake.in
Support for codes porting cuda code that use the .cu extension.
This works for CUDA backend and HIP backend, but requires this
extra option to work with SYCL backend and Intel dpcpp
> cmake: make SYCL backend builds  work with .cu

- CMakeLists.txt
- README.md
- include/gtensor/backend_cuda.h
- include/gtensor/backend_hip.h
- include/gtensor/backend_sycl.h
- include/gtensor/device_backend.h
Set to 'coarse' (default), 'device', or 'fine'. Note that this is
a change to default behavior - previous default was 'fine'.
> config: GTENSOR_MANAGED_MEMORY_TYPE_DEFAULT opt

- CMakeLists.txt
I don't know anyone who's ever used this, and we already support regular installs as well as `add_subdirectory()`, which should suffice.
In particular this causes hassles integrating with other projects via `add_subdirectory()` that don't support buildtree export.
> cmake: don't support old-style buildtree export

- .github/workflows/ccpp.yml
- CMakeLists.txt
- examples/CMakeLists.txt
- examples/Makefile
- examples/src/c_test_fortran.cxx
- examples/src/test_fortran.F90
- include/gtensor/fortran.h
- include/gtensor/fortran/flcl.h
This is basd on kokkos, essentially using their way of passing Fortran arrays (including non-contiguous ones). Adapted to create `gtensor_span` on the C++ side.
> add fortran interoperability

- include/gtensor/backend_common.h
- include/gtensor/backend_cuda.h
- include/gtensor/backend_hip.h
- include/gtensor/backend_host.h
- include/gtensor/backend_sycl.h
- include/gtensor/capi.h
- include/gtensor/device_backend.h
- include/gtensor/gtensor_forward.h
- include/gtensor/gtensor_span.h
- include/gtensor/gtensor_storage.h
- include/gtensor/macros.h
- include/gtensor/space_forward.h
- src/cgtensor.cxx
- tests/test_adapt.cxx
- tests/test_clib.cxx
- tests/test_device_backend.cxx
- tests/test_gtensor_storage.cxx
The main gtensor already mostly supports just using `<space::host>` but various `_device` functionality currently doesn't exist in this case. This starts making it available, where then, e.g. `adapt_device` just acts like `adapt<space::device>` and since `space::device == space::host`, it really just gives you a host gtensor_span, which makes it easier to write code that works with and with an actual gpu.
> add some support for running in host-only mode

- include/gtensor/expression.h
- include/gtensor/gfunction.h
- include/gtensor/gscalar.h
- include/gtensor/gtensor.h
- include/gtensor/gtensor_span.h
- include/gtensor/gview.h
- include/gtensor/helper.h
- tests/test_expression.cxx
Experimental way to add useful debug info, by calling `expr.typestr()`. This is far easier than template meta programming to do this separately, however it has the downside of requiring including string and sstream throughout the code, which I don't like.
> add typestr expression method for debugging

- CMakeLists.txt
- benchmarks/bench_getrf.cxx
- benchmarks/bench_hypz.cxx
- include/gt-blas/backend/host.h
- include/gt-blas/blas.h
- include/gtensor/backend_host.h
- include/gtensor/space.h
- src/cgtblas.cxx
- tests/test_blas.cxx
- tests/test_lapack.cxx
This provides the BLAS interface C++ and C abstractions when compiled host-only. This required quite a bit of
boilerplate code, but oh well...
It only supports OpenBLAS right now, and it's missing `getrf_npvt_batched`, since I can't find anything like that in BLAS/LAPACK.
> interface BLAS on the host

- tests/CMakeLists.txt
- tests/gtest_predicates.h
- tests/test_fft.cxx
- tests/test_gtest_predicates.cxx
Adds overloaded GT_EXPECT_EQ(a, b), GT_EXPECT_NEAR(a, b), and GT_EXPECT_NEAR_MAXERR(a, b, max_err) macros that work with scalars, gtensor expressions, and combinations of the two (expressions must be in first position). The idea is for this to replace the confusingly named test_helpers.h header.
> test: improved test predicates

- include/gtensor/reductions.h
As of rocthrust 5.3.0, the reduce.h header no longer include max_element and transform_reduce. The good news is that the fine grained headers appear to have existed in both cuda nad rocm thrust for a while, so adding them fixes 5.3.0 without breaking older releases.
> reductions: add specific thrust headers

- include/gtensor/sarray.h
A lot of the time, this has been used for shapes etc, where T is an integer type, so it probably wasn't harmful, but still, it's clearly buggy to use `T` for the index type.
> sarray: fix type used for index in operator[]

- include/gtensor/backend_host.h
- include/gtensor/gtensor.h
- tests/test_gtensor.cxx
All it does is allocate a gtensor on the host with matching size.
It does not copy either way, that needs to be done explicitly -- that's one way to allow the user to specify whether they're reading from, or writing to the mirrored gtensor.
> add gt::host_mirror

- .clang-format
- .github/workflows/ccpp.yml
- include/gtensor/device_backend.h
- include/gtensor/macros.h
- src/cgtblas.cxx
- src/cgtensor.cxx
- tests/test_bandsolver.cxx
- tests/test_blas.cxx
- tests/test_cblas.cxx
- tests/test_fft.cxx
- tests/test_lapack.cxx
- tests/test_reductions.cxx
- tests/test_sarray.cxx
- tests/test_sparse.cxx
Starting in v14, short GT_LAMBDA is broken into multiple lines, which creates an inconsistency depending on version used. This change makes it consistent and adds ci checks for both 9 and 14.
> format: single line all functions, dual version ci

- include/gtensor/backend_common.h
- include/gtensor/gtensor.h
- include/gtensor/gtensor_span.h
- tests/test_gtensor.cxx
- tests/test_gtensor_span.cxx
This at least attempts to handle all kinds of different cases how gt::copy may be used. It fixes at least one existing bug
(copies involving non-contiguous gtensor_spans), but now also handles having expressions (rather than just gtensor/gtensor_span) as source and/or destination.
There might still be some cases that I missed, hopefully the kind that will lead to compile time errors, but the cases I handle are all covered by tests, so should be okay.
> improve gt::copy

- include/gtensor/sarray.h
Note that __builtin_unreacheable works on device starting with cuda 11.3
> sarray: silence 0 len no return warning

- CMakeLists.txt
- include/gt-fft/backend/hip.h
More control and simplify dependencies, i.e. make it easier to use a custom built rocfft without having to also build hipfft with the custom rocfft.
> gt-fft: use rocfft instead of hipfft

- benchmarks/bench_fft.cxx
- include/gt-fft/backend/cuda.h
- include/gt-fft/backend/hip.h
- include/gt-fft/backend/sycl.h
- tests/test_fft.cxx
Useful to see if re-using the same buffer between plans and inverse/forward could help with total space used, when concurrency among plans is not needed.
> gt-fft: add get_work_buffer_bytes plan method

- CMakeLists.txt
- include/gtensor/backend_cuda.h
- include/gtensor/backend_hip.h
- include/gtensor/backend_sycl.h
- making prefetch a no-op can improve performance, in particular on AMD platforms
- using prefetch when the default managed memory type is device is pointless, so also make it a no-op in that case even when prefetch is enabled
- prefetch is still enabled by default for other cases
> add GTENSOR_DISABLE_PREFETCH option, mtype check

- include/gtensor/gtensor.h
- include/gtensor/gtensor_span.h
- include/gtensor/gview.h
- tests/test_gtensor.cxx
- tests/test_gtensor_span.cxx
- tests/test_helper.cxx
- tests/test_span.cxx
- tests/test_view.cxx
The data method raises an exception or assert(0) in device code if called on a non-forward-contiguous view.
> view: add view_strided, strided reshape etc overloads

- include/gt-blas/cblas.h
- src/cgtblas.cxx
- tests/test_cblas.cxx
Useful for Fortran applications using both gtblas and gtsolver, should use same handle for all operations on same gpu / stream.
> gt-blas: add gtblas_get_handle to clib

- CMakeLists.txt
Official MKL cmake support works with gtensor tests, but there are some issues when combining with CPU MKL usage, particularly when using needing to use LP64 on CPU and gpu usage (which is always ILP64 independent of which cpu mkl lib is linked).
> sycl: revert to hacked mkl cmake support

- CMakeLists.txt
- cmake/FindFFTW.cmake
- include/gt-fft/backend/fftw_inc.h
- include/gt-fft/backend/host.h
- include/gt-fft/fft.h
This PR makes it possible to use `gt::fft` even if actual GPU support is disabled. It's a prerequisite for building GENE with gtensor support on host-only. The goal isn't production-level support of host-only C++/gtensor GENE, but rather to simplify development of GENE on a local machine does not have GPUs -- because in regular host-only mode,  a lot of parts of GENE aren't even compiled, and obviously not tested. It might be useful for debugging, too.
> add FFT support on host (via fftw)

- include/gtensor/backend_host.h
This doesn't make mem_info work correctly, but at least it fixes the build. Not sure it's worth it to fix this properly, though it could be done.
> workaround mem_info compile error on MacOS

- .github/workflows/ccpp.yml
fixes spurious CI failure on clang cxx20 test. Not sure why this started happening out of the blue, it used to work, and now fails on main branch.
> ci: use clang-15 for cxx20 host test

- tests/test_bandsolver.cxx
In practice race usually only hit for single precision real which finishes fastest.
> tests: fix bandsolver new stream race

- include/gtensor/backend_cuda.h
- include/gtensor/backend_hip.h
For me it seems to be more natural if the get_device_count function returns just 0 in the case of cudaErrorNoDevice and cudaErrorInsufficientDriver. The handling of this case should happen on the applications level, but at the moment the gtensor code aborts.
> Return device_count=0 in error case

- CMakeLists.txt
- include/gtensor/macros.h
- In the `macros.h` file, the error message is added to the error code.
- We use the `CMAKE_HIP_ARCHITECTURES` variable to set the hip architecture for AMD GPUs.
> Clearer error message and HIP architectures
